name: goreleaser

env:
  STAGE: github

on:
  push:
    paths:
      - 'cli/**'
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./cli/
    steps:
      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          ENV_AUTH0_DEVICE_CODE_URL: ${{ secrets.AUTH0_DEVICE_CODE_URL }}
          ENV_AUTH0_TOKEN_URL: ${{ secrets.AUTH0_TOKEN_URL }}
          ENV_AUTH0_URL: ${{ secrets.AUTH0_URL }}
          ENV_AUTH0_USERINFO_URL: ${{ secrets.AUTH0_USERINFO_URL }}
          ENV_FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
          ENV_FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          ENV_FLY_ORG: ${{ secrets.FLY_ORG }}
          ENV_FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          ENV_FRONTEND_URL_AUTH0: ${{ secrets.FRONTEND_URL_AUTH0 }}
          ENV_LOGTAIL_TOKEN: ${{ secrets.LOGTAIL_TOKEN }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: release
        run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.4'
          cache: true
          cache-dependency-path: cli/go.sum
      # More assembly might be required: Docker logins, GPG, etc. It all depends
      # on your needs.
      - uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          workdir: cli
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro'
          # distribution:
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

